// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test-form-success', function() {
  let driver
  let vars

  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    await driver.sleep(300) 
    vars = {}
  })

  afterEach(async function() {
    await driver.quit();
  })

  it('test-form-success', async function() { 
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1417, height: 692 })
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("arthur.chevron4@gmail.com")
    await driver.findElement(By.css(".one-card")).click()
    await driver.findElement(By.name("submit")).click()
    assert(await driver.switchTo().alert().getText() == "sucess")
  })
})
